### ISSUE TITLE
Symbol preview on Symbol and Label tabs are not being updated when entry is double-clicked on Modify tab

### ISSUE THREAD

**Issue by elinz** [Esri/military-symbol-editor-addin-wpf#100]
Testing pull request #98 

I'm using the MIL-STD-2525D map in the Military Overlay template. 

Within the map I select the Fixed-Wing: Cargo: object id 8 feature. The symbol preview is updated on the Modify tab...
![image](https://cloud.githubusercontent.com/assets/4635490/19978837/8a7bae84-a1b5-11e6-92ec-57146ad1b55e.png)

However, when I double-click the entry in the Modify tab, the symbol preview on the Symbol and Label tabs aren't updated to reflect the selected entry...
![image](https://cloud.githubusercontent.com/assets/4635490/19978972/03b461b0-a1b6-11e6-95ec-85c2099d14f9.png)

**Comment by csmoore** [comment]
I do intermittently see this (the symbol loses its affiliation/identity value when selected on map and then changed to symbol/label tabs) - I'll have a look (since this is something I may have broke with my changes)

**Comment by csmoore** [comment]
Another good catch - it turned out selecting symbol sets 01, 02, 05 on modify tab was not
correctly updating the addin (I believe even before the PR).  

Addressed in https://github.com/Esri/military-symbol-editor-addin-wpf/pull/98/commits/5c1abbfa4411daaab21365a42dce0bc01f06eebd and can be retested with the prebuilt addin provided or from daily after the PR merge.

**Comment by Dbarnes1** [comment]
verified, although I'm opening up a similar issue with the modify workflow.
