### ISSUE TITLE
Enhancement: allow for "clear selection" with select button in modify tab

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-symbol-editor-addin-wpf#107]
When I use the symbol editor, I'm unable to clear my selection in the modify tab without using the core clear selection button. It would be nice to have this functionality built in to the modify pane in the add-in. 

If this button could both select AND clear selection that would be great: 
![image](https://cloud.githubusercontent.com/assets/13024357/20018788/7bda8a36-a286-11e6-9b09-88892fd636c5.png)

**Comment by Dbarnes1** [comment]
@csmoore I'm unable to toggle the select button on and off within the modify pane.

**Comment by Dbarnes1** [comment]
@csmoore I can now toggle the select button on and off within the modify pane, but it doesn't automatically unselect any selected features.

Ideally, I would like to:
1. click on the select button in the modify pane (toggle on) and select a feature on the map
2. click on the select button in the modify pane (toggle off) and this action would automatically unselect the feature in both the add-in and on the map

As of right now, you can toggle the select button off in the modify pane, and it will: 
- change the mouse back to "explore" mode
- remove the feature from the modify pane in the add-in
but the feature is still selected on the map

Screenshots for reference
(toggle on):
![image](https://cloud.githubusercontent.com/assets/13024357/21691221/880ac02e-d32c-11e6-878a-eefe3ef9bec2.png)
(toggle off):
![image](https://cloud.githubusercontent.com/assets/13024357/21691242/a0a7c4c4-d32c-11e6-8439-64e67072c176.png)

**Comment by csmoore** [comment]
@Dbarnes1 - that is indeed how it was *supposed* to work.  This does work on 1.2, but I do now see that on 1.4 things are misbehaving. 

The source of this problem is that this callback is now being called on a non-UI thread at 1.4 for some odd reason so the [ClearSelection command isn't working now](https://github.com/Esri/military-symbol-editor-addin-wpf/blob/dev/source/ProSymbolEditor/ViewModels/MilitarySymbolDockpaneViewModel.cs#L896) - looking into how to refactor the code to guarantee it is called on UI thread.

**Comment by csmoore** [comment]
@Dbarnes1 - hopefully this is finally fixed now in the next build.

**Comment by Dbarnes1** [comment]
verified ! 
closing.
