### ISSUE TITLE
Style file for 2525Bc2 does not allow a higher formation value

### ISSUE THREAD

**Issue by dfoll** [Esri/military-symbol-editor-addin-wpf#161]
When trying to create a unit in 2525Bc2, if you enter a value for higher formation it is not displaying, whether you use the label tab to enter the value, or if you place the symbol on the map first and then use the attribute window to assign the value

**Comment by dfoll** [comment]
@Dbarnes1 is that a clear enough way to state the problem?

**Comment by Dbarnes1** [comment]
@dfoll this makes sense, and I'm aware that it is a stylx issue, so technically this is more of a mil-features-data repo issue but I'll put it on my list to take care of regardless.

**Comment by Dbarnes1** [comment]
@dfoll I'm actually unable to repro at this point.

**Comment by joebayles** [comment]
@dfoll @Dbarnes1 I was able to reproduce this. There are a few dynamics at play here:

@Dbarnes1 was not able to reproduce this because the stylx on his version of Pro has been modified. From a fresh install of Pro 1.4 Final and Military Tools  1.0.0, I can't get Higher Formation to show up. With the stylx that @Dbarnes1 provided me, it works great.

This leads me to believe that the stylx that shipped in Pro is not the latest one that was provided to the Pro team prior to 1.4 release.

Suggestion: Provide an explanation, instructions on how to update the stylx, and a download link on the solutions website.

FYI it works in Pro 2.0, according to @Dbarnes1.

**Comment by dfoll** [comment]
This needs to be fixed by Jenkins adding the correct stylx file to the build.

**Comment by dfoll** [comment]
because this is an issue that is largely out of the military tools team's hands this has been handled with documentation both in the known issues and a section explaining how to get around it, please verify documentation exists and is clear

**Comment by dfoll** [comment]
@topowright moving this to closed, since i sat next to you while you did this, and we just forgot to move it to closed
