### ISSUE TITLE
Modify tab Dark theme visibility

### ISSUE THREAD

**Issue by dfoll** [Esri/military-symbol-editor-addin-wpf#163]
- [ ] Symbol Attribute table is white, it should be dark gray with white text like the regular attributes window
![image](https://cloud.githubusercontent.com/assets/5322669/26515146/b501fb00-422c-11e7-93f3-e5939c0dd6d7.png)
(currently)
![image](https://cloud.githubusercontent.com/assets/5322669/26515154/c4accd14-422c-11e7-8f86-1b71b5e5a357.png)
(should look like this)

**Comment by csmoore** [comment]
To resolve the issues with the Attribute Display table, switching this from the Open Source Exceed.wpftoolkit.PropertyGrid (which didn't have theme support in the open source version) to a regular datagrid (which Pro provides a style for) - this is how it should look after the changes:

![image](https://user-images.githubusercontent.com/3090809/34182283-9780b3fa-e4e3-11e7-884d-c9292ae887af.png)

It should work a little better than before since we can hide/remove the null/empty entries and update the datagrid better.

**Comment by csmoore** [comment]
Addressed in  #207, should look this now on this tab:

![image](https://user-images.githubusercontent.com/3090809/34221596-937098f4-e586-11e7-9969-6e2643507615.png)

Also addressed issue where property control was visible when there was no selection.

Ready to test once #207 merged/built.
