### ISSUE TITLE
Label tab Dark theme visibility

### ISSUE THREAD

**Issue by dfoll** [Esri/military-symbol-editor-addin-wpf#166]
- [x] some of the input boxes are white, they should match dark theme input boxes 
![image](https://cloud.githubusercontent.com/assets/5322669/26515304/70d01e9c-422e-11e7-94a5-60f2386e863d.png)
(currently)
![image](https://cloud.githubusercontent.com/assets/5322669/26515306/78febd94-422e-11e7-858f-cd1c25cc77bc.png)
(they should all match the dark theme style)

- [x] Symbol Attributes table is white, it should match the regular dark them Attributes table
![image](https://cloud.githubusercontent.com/assets/5322669/26515318/9c268e5a-422e-11e7-8555-97c662a44544.png)
(currently)
![image](https://cloud.githubusercontent.com/assets/5322669/26515323/a3840754-422e-11e7-91c8-33608d08d9d1.png)
(should match this style)

- [x] Add to Map button is white should match the other dark theme buttons
![image](https://cloud.githubusercontent.com/assets/5322669/26515334/b93cc054-422e-11e7-9f52-98d9d3f8ec5c.png)
(Add to Map should match Add to Favorite)

**Comment by csmoore** [comment]
Issues noted above addressed in #206 , #207 

![image](https://user-images.githubusercontent.com/3090809/34233513-ddb3c1a2-e5b3-11e7-8147-6a8033a60abb.png)

There is an additional issue not noted - with the 3rd party WPF Toolkit Date/Time Control (calendar) and spin buttons (up/down arrows) not being in dark theme - I don't think I will be able to address these without removing the Date/Time Control because this is the only compelling open source Date/Time Control available.
