### ISSUE TITLE
Remove the duplicate type from the search component 

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbol-editor-addin-wpf#187]
Currently when you search for a symbol you can only search for a symbol with the affiliation  set to *, which brings up five choices for the user to select from: 

![image](https://user-images.githubusercontent.com/5488313/27416383-f359550c-56c1-11e7-831d-14d116aa130b.png)

The first choice and the unknown choice are the same thing from what I can understand by selecting both. I think the first choice should go away and we should only give the option of: 

Friendly
Neutral
Hostile
Unknown.

**Comment by csmoore** [comment]
I'm not sure this is a bug. The search is returning the items in the style that have that tag (there are 5 items in the style that match this tag as shown). 

The reason the 1st item has an unknown affiliation is because there is no affiliation tag so it can't be determined/inferred like the other 4.

**Comment by topowright** [comment]
@csmoore remvoed the bug tag and placed the enhancement tag on this issue.

**Comment by topowright** [comment]
This can be closed.
